### ISSUE TITLE
JetBrains URL changes

### ISSUE THREAD

**Issue by merced317** [jarias/autopkg-munki-recipes#1]
https://www.jetbrains.com/idea/download/download-thanks.html?platform=mac&code=IIC
https://www.jetbrains.com/pycharm/download/download-thanks.html?platform=mac&code=PCC

There are likely others, but those are the two I use.  Would appreciate an update to the munki recipes.  Thanks!

**Comment by jarias** [comment]
Sure pull request are also welcome ;)

**Comment by merced317** [comment]
https://github.com/jarias/autopkg-munki-recipes/pull/2

I'm new to all this github stuff.  Hopefully I did this right.

**Comment by merced317** [comment]
Crud.  The new URLs don't include a parseable string for the download URL.  It's obfuscated.  Example:

<a data-release-download-link="">direct link</a>

Autopkg now produces a "No match found on URL" error.  Trying to figure this out.

Facebook's method for detecting the download URL doesn't work either.

https://github.com/facebook/Recipes-for-AutoPkg/tree/master/Intellij

The URL they use does not appear to be maintained.  https://www.jetbrains.com/js2/version.js

**Comment by jarias** [comment]
Yeah the problem is that the href is filled up using JavaScript, the only workaround I can think of is hardcoding the URL which would require manual updates every time a new version is release.

**Comment by merced317** [comment]
Looking at this:

https://github.com/ubuntu/ubuntu-make/blob/master/umake/frameworks/ide.py

If you look at line 148, it shows the new URL that can be used to determine the download.  The rest shows what "code" to put into the URL to get the download links.  If I have time, I'll look into using this to patch the autopkg recipes.

**Comment by jarias** [comment]
That's very cool, thanks for the info. If you can take a shot at it would be great, I don't have a lot of python experience but I could try to give a shot after Christmas.

**Comment by jarias** [comment]
@merced317 I had some free time, I went ahead and updated the recipes, I test a couple, If you can test them all that would be really helpful, and if they work go ahead and close the issue.

Thanks for the research.

**Comment by merced317** [comment]
The PyCharm links should no longer have the "-custom" in the file name.  Other than that, I think all are working.  Thanks for updating as I really had no free time today to look into it.
